language: python
python:
  - "3.6.4"
# command to run tests
install:
  - pip install -r requirements.txt
script: nosetests -v

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" ### AWS region of your choice
  app: "easycrm-test" ### Your EB App name
  env: "easycrmtest-test-env" ### Your EB App environment name
  bucket_name: "elasticbeanstalk-us-east-1-536501238579" ### S3 bucket name
  bucket_path: "easycrm" ### S3 folder name under S3 bucket above
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
